import { Article } from './article.model';

export const ARTICLES: Article[]=[
  new Article("Man sues Dunkin' Donuts after asking for real butter, getting a substitute","Associated Press","A Massachusetts man who sued a pair of Dunkin' Donuts owners because he said he was given a butter substitute when he asked for real butter on his bagel has won a settlement.\rThe Boston Globe (http://bit.ly/2ogQP2u ) reports that Jan Polanik's suits name two companies that together own more than 20 stores.\rPolanik's lawyer, Thomas Shapiro, acknowledged that his client's complaint is \"a minor thing,\" but they decided to sue \"to stop the practice of representing one thing and selling a different thing.\"\rShapiro did not disclose the settlement's terms, because it hasn't yet been filed with the court.\rAn attorney for one franchisee confirms that the case has been settled and the stores have changed their butter-serving protocol. A spokesman for the other franchisee could not be reached.",true, 1),
  new Article("Chinese engineer ‘marries’ robot after failing to find a human wife","Kristin Huang","A Chinese engineer has “married” a robot he created after failing to find a human spouse.\rZheng Jiajia, 31, an artificial intelligence expert who designs and creates robots in Hangzhou, Zhejiang province, created the “female” robot at the end of last year, the Qianjiang Evening News reported.\rThe robot, which he named Yingying, can identify Chinese characters and images and even say a few simple words, the report said.\rZheng “married” his creation in a simple ceremony on Friday, according to the report.\rYingying wore a black suit on the day and “her”head was covered with a red scarf during the ceremony, a traditional Chinese wedding ritual.",true, 2),
  new Article("Former Enron exec advises TCU students to do the right thing","STEVE KASKOVICH","Andy Fastow has two props he uses in speeches to explain how he ended up as one of the country’s most famous corporate criminals.\rFirst, he holds up the trophy he received when he was named “CFO of the Year” in 2000 for his work at Enron Corp. Then he holds up the federal prison ID card he was issued when he served nearly six years for wire and securities fraud.\r“I got both of these for doing the same deals,” Fastow told a roomful of business students at Texas Christian University on Tuesday. “How is it possible to be CFO of the Year and commit the greatest fraud in American history doing the same deals?”\rTo Fastow, it comes down to one word: loopholes.\rWhile serving as Enron’s chief financial officer from 1998 to 2001, Fastow created a web of off-balance-sheet entities that turned the Houston pipeline company into what seemed like a highly profitable trading powerhouse. But in a span of four months in 2001, Enron went from near the top of the Fortune 500 to bankruptcy, spawning investigations that led to criminal charges for its top executives.",true, 3),
  new Article("Health Scare Prompts Man To Start Overeating Healthier","The Onion","ROUND ROCK, TX—Having recently learned from his doctor that he suffered from high blood pressure and elevated cholesterol levels that put him at serious risk for cardiovascular disease and stroke, 43-year-old Donald Fisher told reporters Thursday the unanticipated health scare had prompted him to start overeating healthier. “This has been a real wake-up call for me, so from now on, I’m sticking to eating only nutritious, low-fat foods well past the point of feeling full,” said Fisher, explaining that he had already cut oversized portions of red meat out of his diet in favor of multiple hulking servings of lean proteins such as fish, beans, and baked chicken. “It’s not going to be easy, but if I can replace my regular afternoon snack of Doritos with a whole bag of organic kale chips and restrict myself to five or six helpings from just the salad bar when I go out to eat at a buffet, I should be okay. I’ve really got to make these big changes; this is my health we’re talking about here.” At press time, Fisher was attempting to slake a late-night bout of hunger with 900 calories’ worth of apples and peanut butter.",false, 4),
  new Article("Mike Pence Asks Waiter To Remove Mrs. Butterworth From Table Until Wife Arrives","The Onion","Expressing concerns about the propriety of being left alone with a syrup container of the opposite sex, Vice President Mike Pence reportedly asked his waiter Thursday to remove Mrs. Butterworth from the table until his wife arrived to join him at a local diner. “Excuse me, sir, would you please take this out of my line of sight until my wife gets here?” said Pence, who reportedly attempted to put the table’s sugar dispenser and salt and pepper shakers between him and the feminine syrup bottle before deciding that even having Mrs. Butterworth within arm’s reach could lead him to have impure thoughts. “It just would not be right for me to sit here alone with a woman-shaped container, particularly one as shapely as this. In fact, I would advise you to do the same for the man sitting over there—I see he is sitting very close to Mrs. Butterworth even though he appears to be wearing a wedding ring.” At press time, Pence had asked the waiter to pour syrup on his pancakes for him, as it would be unseemly to handle the curves of the plastic woman in such a public place.",false, 5),


]
